// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCXYtcxvEb1dYpLv2q-uDZYQBEnyHqv-zY',
    appId: '1:901368737444:web:518e16266f530961dd0031',
    messagingSenderId: '901368737444',
    projectId: 'priorli',
    authDomain: 'priorli.firebaseapp.com',
    databaseURL: 'https://priorli-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'priorli.appspot.com',
    measurementId: 'G-TZ8XYQ8MB4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD7RctYqzHJ4XjuwOGqPXGI4GgDLJzl7ls',
    appId: '1:901368737444:android:787ca89f38c7b283dd0031',
    messagingSenderId: '901368737444',
    projectId: 'priorli',
    databaseURL: 'https://priorli-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'priorli.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDICYSBX72uw7Iv6aJoFEYyerJtfnqgNqM',
    appId: '1:901368737444:ios:dda86e898c89d17cdd0031',
    messagingSenderId: '901368737444',
    projectId: 'priorli',
    databaseURL: 'https://priorli-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'priorli.appspot.com',
    androidClientId: '901368737444-qfjdrmlho3peevv1qj7uu5th9nt1a9q3.apps.googleusercontent.com',
    iosClientId: '901368737444-b09itlqartqotjg81c5qpu5eurctei74.apps.googleusercontent.com',
    iosBundleId: 'com.priorli.priorli',
  );
}
